/*
 * Dummy schema for Plamenix dev/testing.
 * Entrypoint pipes this file into the freshly-created
 * /var/lib/firebird/data/test.fdb via isql.
 */

/* ─── DOMAINS ────────────────────────────────────────────────── */

CREATE DOMAIN D_EMAIL AS VARCHAR(255)
  CHECK (VALUE LIKE '%@%');

CREATE DOMAIN D_MONEY AS NUMERIC(15, 2)
  DEFAULT 0
  CHECK (VALUE >= 0);

CREATE DOMAIN D_BOOL_FLAG AS SMALLINT
  DEFAULT 0
  CHECK (VALUE IN (0, 1))
  NOT NULL;

/* ─── GENERATORS (SEQUENCES) ─────────────────────────────────── */

CREATE GENERATOR GEN_CUSTOMERS_ID;
CREATE GENERATOR GEN_ORDERS_ID;
CREATE GENERATOR GEN_PRODUCTS_ID;

/* ─── TABLES ─────────────────────────────────────────────────── */

CREATE TABLE CUSTOMERS (
  ID         INTEGER NOT NULL PRIMARY KEY,
  NAME       VARCHAR(120) NOT NULL,
  EMAIL      D_EMAIL,
  ACTIVE     D_BOOL_FLAG,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE PRODUCTS (
  ID        INTEGER NOT NULL PRIMARY KEY,
  SKU       VARCHAR(40) NOT NULL UNIQUE,
  NAME      VARCHAR(200) NOT NULL,
  PRICE     D_MONEY NOT NULL,
  IN_STOCK  D_BOOL_FLAG
);

CREATE TABLE ORDERS (
  ID           INTEGER NOT NULL PRIMARY KEY,
  CUSTOMER_ID  INTEGER NOT NULL REFERENCES CUSTOMERS(ID),
  PLACED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  TOTAL        D_MONEY NOT NULL,
  STATUS       VARCHAR(20) DEFAULT 'pending' NOT NULL
);

CREATE TABLE ORDER_ITEMS (
  ORDER_ID    INTEGER NOT NULL REFERENCES ORDERS(ID) ON DELETE CASCADE,
  PRODUCT_ID  INTEGER NOT NULL REFERENCES PRODUCTS(ID),
  QUANTITY    INTEGER NOT NULL CHECK (QUANTITY > 0),
  PRIMARY KEY (ORDER_ID, PRODUCT_ID)
);

/* ─── TRIGGERS (id assignment from generators) ───────────────── */

SET TERM ^;

CREATE TRIGGER BI_CUSTOMERS FOR CUSTOMERS
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_CUSTOMERS_ID, 1);
END^

CREATE TRIGGER BI_PRODUCTS FOR PRODUCTS
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_PRODUCTS_ID, 1);
END^

CREATE TRIGGER BI_ORDERS FOR ORDERS
ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_ORDERS_ID, 1);
END^

/* ─── PROCEDURES ─────────────────────────────────────────────── */

CREATE PROCEDURE SP_PLACE_ORDER (
  P_CUSTOMER_ID INTEGER,
  P_PRODUCT_ID  INTEGER,
  P_QUANTITY    INTEGER
)
RETURNS (
  ORDER_ID INTEGER,
  TOTAL    NUMERIC(15, 2)
)
AS
DECLARE VARIABLE UNIT_PRICE NUMERIC(15, 2);
BEGIN
  SELECT PRICE FROM PRODUCTS WHERE ID = :P_PRODUCT_ID INTO :UNIT_PRICE;
  TOTAL = UNIT_PRICE * P_QUANTITY;

  INSERT INTO ORDERS (CUSTOMER_ID, TOTAL)
    VALUES (:P_CUSTOMER_ID, :TOTAL)
    RETURNING ID INTO :ORDER_ID;

  INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY)
    VALUES (:ORDER_ID, :P_PRODUCT_ID, :P_QUANTITY);

  SUSPEND;
END^

CREATE PROCEDURE SP_CUSTOMER_TOTALS (
  P_CUSTOMER_ID INTEGER
)
RETURNS (
  ORDER_COUNT INTEGER,
  GRAND_TOTAL NUMERIC(15, 2)
)
AS
BEGIN
  SELECT COUNT(*), COALESCE(SUM(TOTAL), 0)
    FROM ORDERS
    WHERE CUSTOMER_ID = :P_CUSTOMER_ID
    INTO :ORDER_COUNT, :GRAND_TOTAL;
  SUSPEND;
END^

SET TERM ;^

COMMIT;

/* ─── VIEWS ──────────────────────────────────────────────────── */

CREATE VIEW V_ACTIVE_CUSTOMERS AS
  SELECT ID, NAME, EMAIL, CREATED_AT
    FROM CUSTOMERS
    WHERE ACTIVE = 1;

CREATE VIEW V_RECENT_ORDERS AS
  SELECT O.ID         AS ORDER_ID,
         C.NAME       AS CUSTOMER_NAME,
         O.PLACED_AT,
         O.TOTAL,
         O.STATUS
    FROM ORDERS O
    JOIN CUSTOMERS C ON C.ID = O.CUSTOMER_ID;

CREATE VIEW V_PRODUCT_REVENUE AS
  SELECT P.SKU,
         P.NAME,
         SUM(OI.QUANTITY) AS UNITS_SOLD,
         SUM(OI.QUANTITY * P.PRICE) AS REVENUE
    FROM PRODUCTS P
    JOIN ORDER_ITEMS OI ON OI.PRODUCT_ID = P.ID
    GROUP BY P.SKU, P.NAME;

/* ─── SEED DATA ──────────────────────────────────────────────── */

INSERT INTO CUSTOMERS (NAME, EMAIL, ACTIVE)
  VALUES ('Alice Anderson', 'alice@example.com', 1);
INSERT INTO CUSTOMERS (NAME, EMAIL, ACTIVE)
  VALUES ('Bob Barker',     'bob@example.com',   1);
INSERT INTO CUSTOMERS (NAME, EMAIL, ACTIVE)
  VALUES ('Carol Carlson',  'carol@example.com', 0);

INSERT INTO PRODUCTS (SKU, NAME, PRICE, IN_STOCK)
  VALUES ('SKU-001', 'Plamenix T-Shirt', 24.99, 1);
INSERT INTO PRODUCTS (SKU, NAME, PRICE, IN_STOCK)
  VALUES ('SKU-002', 'Firebird Mug',      9.50, 1);
INSERT INTO PRODUCTS (SKU, NAME, PRICE, IN_STOCK)
  VALUES ('SKU-003', 'SQL Sticker Pack',  4.75, 0);

COMMIT;

/* Two sample orders via the procedure. */
EXECUTE PROCEDURE SP_PLACE_ORDER (1, 1, 2);
EXECUTE PROCEDURE SP_PLACE_ORDER (2, 2, 5);

COMMIT;
