/* Plamenix test-database seed.
 *
 * Adds domains, generators, a demo table, stored procedures, and
 * triggers so the schema browser surfaces every node kind. Designed
 * for a fresh attach; reruns will fail on duplicates — drop the
 * objects (see TEARDOWN below) before re-seeding.
 *
 * Run from the host with `isql`:
 *
 *     isql -u SYSDBA -p masterkey \
 *         /var/lib/firebird/data/test.fdb \
 *         -i path/to/seed-test.sql
 *
 * Inside Plamenix's editor the embedded `;` characters in PSQL bodies
 * confuse the host's statement splitter, so prefer `isql` (which honours
 * SET TERM) for the initial seed.
 */

SET TERM ^ ;

/* -------- DOMAINS ---------------------------------------------- */

CREATE DOMAIN D_EMAIL AS VARCHAR(254)
    CHECK (POSITION('@' IN VALUE) > 1)^

CREATE DOMAIN D_MONEY AS NUMERIC(18, 2) DEFAULT 0 NOT NULL^

CREATE DOMAIN D_PCT AS SMALLINT
    CHECK (VALUE BETWEEN 0 AND 100)^

CREATE DOMAIN D_STATUS AS VARCHAR(16) DEFAULT 'pending' NOT NULL
    CHECK (VALUE IN ('pending', 'active', 'archived'))^

/* -------- GENERATORS ------------------------------------------- */

CREATE GENERATOR GEN_PMX_USERS^
ALTER GENERATOR GEN_PMX_USERS RESTART WITH 1000^

CREATE GENERATOR GEN_PMX_ORDERS_ID^
ALTER GENERATOR GEN_PMX_ORDERS_ID RESTART WITH 1^

CREATE GENERATOR GEN_AUDIT_SEQ^

/* -------- TABLES ----------------------------------------------- */

CREATE TABLE PMX_USERS (
    ID          INTEGER NOT NULL PRIMARY KEY,
    EMAIL       D_EMAIL NOT NULL,
    DISPLAY     VARCHAR(80) NOT NULL,
    STATUS      D_STATUS,
    BALANCE     D_MONEY,
    DISCOUNT    D_PCT,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP
)^

CREATE TABLE PMX_ORDERS (
    ID          INTEGER NOT NULL PRIMARY KEY,
    USER_ID     INTEGER NOT NULL REFERENCES PMX_USERS (ID),
    AMOUNT      D_MONEY,
    STATUS      D_STATUS,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)^

CREATE TABLE PMX_AUDIT_LOG (
    SEQ         INTEGER NOT NULL PRIMARY KEY,
    ENTITY      VARCHAR(32) NOT NULL,
    ENTITY_ID   INTEGER,
    ACTION      VARCHAR(16) NOT NULL,
    LOGGED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)^

/* -------- PROCEDURES ------------------------------------------- */

CREATE PROCEDURE SP_ADD_USER (
    IN_EMAIL  D_EMAIL,
    IN_NAME   VARCHAR(80)
)
RETURNS (
    NEW_ID    INTEGER
)
AS
BEGIN
    NEW_ID = NEXT VALUE FOR GEN_PMX_USERS;
    INSERT INTO PMX_USERS (ID, EMAIL, DISPLAY)
        VALUES (:NEW_ID, :IN_EMAIL, :IN_NAME);
    SUSPEND;
END^

CREATE PROCEDURE SP_TOUCH_USER (
    IN_ID  INTEGER
)
AS
BEGIN
    UPDATE PMX_USERS SET UPDATED_AT = CURRENT_TIMESTAMP WHERE ID = :IN_ID;
END^

CREATE PROCEDURE SP_TOP_PMX_USERS (
    LIMIT_N  INTEGER
)
RETURNS (
    ID       INTEGER,
    DISPLAY  VARCHAR(80),
    BALANCE  D_MONEY
)
AS
BEGIN
    FOR SELECT ID, DISPLAY, BALANCE FROM PMX_USERS
        ORDER BY BALANCE DESC
        ROWS 1 TO :LIMIT_N
        INTO :ID, :DISPLAY, :BALANCE
    DO
        SUSPEND;
END^

CREATE PROCEDURE SP_USER_STATS
RETURNS (
    TOTAL   INTEGER,
    ACTIVE  INTEGER
)
AS
BEGIN
    SELECT COUNT(*), COUNT(*) FILTER (WHERE STATUS = 'active')
        FROM PMX_USERS INTO :TOTAL, :ACTIVE;
    SUSPEND;
END^

/* -------- TRIGGERS --------------------------------------------- */

CREATE TRIGGER T_PMX_USERS_BI FOR PMX_USERS
    ACTIVE BEFORE INSERT
    POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR GEN_PMX_USERS;
END^

CREATE TRIGGER T_PMX_USERS_BU FOR PMX_USERS
    ACTIVE BEFORE UPDATE
    POSITION 0
AS
BEGIN
    NEW.UPDATED_AT = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER T_PMX_USERS_AIU FOR PMX_USERS
    ACTIVE AFTER INSERT OR UPDATE
    POSITION 10
AS
BEGIN
    INSERT INTO PMX_AUDIT_LOG (SEQ, ENTITY, ENTITY_ID, ACTION)
        VALUES (NEXT VALUE FOR GEN_AUDIT_SEQ, 'USER', NEW.ID,
                CASE WHEN OLD.ID IS NULL THEN 'insert' ELSE 'update' END);
END^

CREATE TRIGGER T_PMX_USERS_AD FOR PMX_USERS
    ACTIVE AFTER DELETE
    POSITION 0
AS
BEGIN
    INSERT INTO PMX_AUDIT_LOG (SEQ, ENTITY, ENTITY_ID, ACTION)
        VALUES (NEXT VALUE FOR GEN_AUDIT_SEQ, 'USER', OLD.ID, 'delete');
END^

CREATE TRIGGER T_PMX_ORDERS_BI FOR PMX_ORDERS
    ACTIVE BEFORE INSERT
    POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR GEN_PMX_ORDERS_ID;
END^

CREATE TRIGGER T_PMX_ORDERS_AIUD FOR PMX_ORDERS
    ACTIVE AFTER INSERT OR UPDATE OR DELETE
    POSITION 0
AS
BEGIN
    INSERT INTO PMX_AUDIT_LOG (SEQ, ENTITY, ENTITY_ID, ACTION)
        VALUES (NEXT VALUE FOR GEN_AUDIT_SEQ, 'ORDER',
                COALESCE(NEW.ID, OLD.ID),
                CASE
                    WHEN OLD.ID IS NULL THEN 'insert'
                    WHEN NEW.ID IS NULL THEN 'delete'
                    ELSE 'update'
                END);
END^

CREATE TRIGGER T_PMX_ORDERS_DISABLED FOR PMX_ORDERS
    INACTIVE BEFORE INSERT
    POSITION 100
AS
BEGIN
    /* Sample inactive trigger so the sidebar shows the strikethrough
     * state. Toggle ACTIVE through the right-click menu to enable it. */
    NEW.STATUS = 'pending';
END^

/* -------- DEMO DATA ------------------------------------------- */

INSERT INTO PMX_USERS (ID, EMAIL, DISPLAY, STATUS, BALANCE, DISCOUNT)
    VALUES (1, 'alice@example.test', 'Alice', 'active', 1200.50, 10)^
INSERT INTO PMX_USERS (ID, EMAIL, DISPLAY, STATUS, BALANCE, DISCOUNT)
    VALUES (2, 'bob@example.test',   'Bob',   'pending', 0,      0)^
INSERT INTO PMX_USERS (ID, EMAIL, DISPLAY, STATUS, BALANCE, DISCOUNT)
    VALUES (3, 'carol@example.test', 'Carol', 'archived', 99.99, 25)^

INSERT INTO PMX_ORDERS (ID, USER_ID, AMOUNT, STATUS)
    VALUES (1, 1, 250.00, 'active')^
INSERT INTO PMX_ORDERS (ID, USER_ID, AMOUNT, STATUS)
    VALUES (2, 1, 950.50, 'archived')^
INSERT INTO PMX_ORDERS (ID, USER_ID, AMOUNT, STATUS)
    VALUES (3, 3, 99.99,  'archived')^

COMMIT^

SET TERM ; ^

/* -------- TEARDOWN (uncomment to wipe before re-seeding) --------
DROP TRIGGER T_PMX_USERS_BI;
DROP TRIGGER T_PMX_USERS_BU;
DROP TRIGGER T_PMX_USERS_AIU;
DROP TRIGGER T_PMX_USERS_AD;
DROP TRIGGER T_PMX_ORDERS_BI;
DROP TRIGGER T_PMX_ORDERS_AIUD;
DROP TRIGGER T_PMX_ORDERS_DISABLED;
DROP PROCEDURE SP_ADD_USER;
DROP PROCEDURE SP_TOUCH_USER;
DROP PROCEDURE SP_TOP_PMX_USERS;
DROP PROCEDURE SP_USER_STATS;
DROP TABLE PMX_ORDERS;
DROP TABLE PMX_AUDIT_LOG;
DROP TABLE PMX_USERS;
DROP GENERATOR GEN_PMX_USERS;
DROP GENERATOR GEN_PMX_ORDERS_ID;
DROP GENERATOR GEN_AUDIT_SEQ;
DROP DOMAIN D_EMAIL;
DROP DOMAIN D_MONEY;
DROP DOMAIN D_PCT;
DROP DOMAIN D_STATUS;
COMMIT;
*/
